import { ElectionType, StateElectionData, StateStats } from './types';

export const electionData: Record<string, StateElectionData> = {
  uttarpradesh: {
    stateName: 'Uttar Pradesh',
    availableElections: [
      {
        name: 'Uttar Pradesh Assembly General Election 2017',
        type: ElectionType.Assembly,
        surveyDate: '11-03-2017',
        estimatedColumn: 'Estimates on 09-03-2017 after calculations',
        actualColumn: 'Actual seats received on 11-03-2017',
        rulingParty: 'BJP',
      },
    ],
  },
  andhrapradesh: {
    stateName: 'Andhra Pradesh',
    availableElections: [
      {
        name: 'Andhra Pradesh Assembly Election 2024',
        type: ElectionType.Assembly,
        estimatedColumn: 'Expected Seats',
        actualColumn: 'Actual Seats',
        rulingParty: 'YSRCP',
        partyNameColumns: ['Party Name', 'Expected Winner (SGED)', 'Actual Winner 2024'],
      },
      {
        name: 'Andhra Pradesh Lok Sabha Election 2024',
        type: ElectionType.LokSabha,
        estimatedColumn: 'Expected Total Seats / Predicted Seats',
        actualColumn: 'Actual Results 2024',
        rulingParty: 'YSRCP',
        partyNameColumns: ['Party Name', 'Winning Party Predicted', 'Winning Party Actual'],
      },
    ],
  },
  bihar: {
    stateName: 'Bihar',
    availableElections: [
      {
        name: 'Bihar Legislative Assembly Election 2025',
        type: ElectionType.Assembly,
        estimatedColumn: 'Estimated Seats Prediction',
        actualColumn: 'Actual Seats After Results on 14-11-2025',
        mergeColumns: [
          'Alliance',
          'District',
          'Expected Total Seats',
          'Actual Total Seats After Results 14-11-2025',
          'After Adjustment With Variation By PPA',
          'Differences',
        ],
        rulingParty: 'BJP',
      },
    ],
  },
  tamilnadu: {
    stateName: 'Tamil Nadu',
    availableElections: [
      {
        name: 'Tamil Nadu Assembly Election 2026',
        type: ElectionType.Assembly,
        estimatedColumn: 'Estimated Seats Prediction',
        actualColumn: 'Actual Seats After Results on 14-11-2025',
        isUpcoming: true,
      },
    ],
  },
  westbengal: {
    stateName: 'West Bengal',
    availableElections: [
      {
        name: 'West Bengal Assembly Election 2026',
        type: ElectionType.Assembly,
        estimatedColumn: 'Estimated Seats Prediction',
        actualColumn: 'Actual Seats After Results on 14-11-2025',
        isUpcoming: true,
      },
    ],
  },
};

export const stateStats: Record<string, StateStats> = {
  andhrapradesh: {
    name: 'Andhra Pradesh',
    mlas: 175,
    mpsLokSabha: 25,
    ulbs: 125,
    rajyaSabha: 11,
    legislativeCouncil: 58,
  },
  arunachalpradesh: {
    name: 'Arunachal Pradesh',
    mlas: 60,
    mpsLokSabha: 2,
    ulbs: 35,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  assam: {
    name: 'Assam',
    mlas: 126,
    mpsLokSabha: 14,
    ulbs: 102,
    rajyaSabha: 7,
    legislativeCouncil: 0,
  },
  bihar: {
    name: 'Bihar',
    mlas: 243,
    mpsLokSabha: 40,
    ulbs: 252,
    rajyaSabha: 16,
    legislativeCouncil: 75,
  },
  chhattisgarh: {
    name: 'Chhattisgarh',
    mlas: 90,
    mpsLokSabha: 11,
    ulbs: 170,
    rajyaSabha: 5,
    legislativeCouncil: 0,
  },
  goa: {
    name: 'Goa',
    mlas: 40,
    mpsLokSabha: 2,
    ulbs: 14,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  gujarat: {
    name: 'Gujarat',
    mlas: 182,
    mpsLokSabha: 26,
    ulbs: 166,
    rajyaSabha: 11,
    legislativeCouncil: 0,
  },
  haryana: {
    name: 'Haryana',
    mlas: 90,
    mpsLokSabha: 10,
    ulbs: 92,
    rajyaSabha: 5,
    legislativeCouncil: 0,
  },
  himachalpradesh: {
    name: 'Himachal Pradesh',
    mlas: 68,
    mpsLokSabha: 4,
    ulbs: 68,
    rajyaSabha: 3,
    legislativeCouncil: 0,
  },
  jharkhand: {
    name: 'Jharkhand',
    mlas: 81,
    mpsLokSabha: 14,
    ulbs: 52,
    rajyaSabha: 6,
    legislativeCouncil: 0,
  },
  karnataka: {
    name: 'Karnataka',
    mlas: 224,
    mpsLokSabha: 28,
    ulbs: 313,
    rajyaSabha: 12,
    legislativeCouncil: 75,
  },
  kerala: {
    name: 'Kerala',
    mlas: 140,
    mpsLokSabha: 20,
    ulbs: 96,
    rajyaSabha: 9,
    legislativeCouncil: 0,
  },
  ladakh: {
    name: 'Ladakh',
    mlas: 1,
    mpsLokSabha: 1,
    ulbs: 0,
    rajyaSabha: 0,
    legislativeCouncil: 0,
  },
  madhyapradesh: {
    name: 'Madhya Pradesh',
    mlas: 230,
    mpsLokSabha: 29,
    ulbs: 414,
    rajyaSabha: 11,
    legislativeCouncil: 0,
  },
  maharashtra: {
    name: 'Maharashtra',
    mlas: 288,
    mpsLokSabha: 48,
    ulbs: 407,
    rajyaSabha: 19,
    legislativeCouncil: 78,
  },
  manipur: {
    name: 'Manipur',
    mlas: 60,
    mpsLokSabha: 2,
    ulbs: 27,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  meghalaya: {
    name: 'Meghalaya',
    mlas: 60,
    mpsLokSabha: 2,
    ulbs: 12,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  mizoram: {
    name: 'Mizoram',
    mlas: 40,
    mpsLokSabha: 1,
    ulbs: 23,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  nagaland: {
    name: 'Nagaland',
    mlas: 60,
    mpsLokSabha: 1,
    ulbs: 39,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  odisha: {
    name: 'Odisha',
    mlas: 147,
    mpsLokSabha: 21,
    ulbs: 114,
    rajyaSabha: 10,
    legislativeCouncil: 0,
  },
  punjab: {
    name: 'Punjab',
    mlas: 117,
    mpsLokSabha: 13,
    ulbs: 169,
    rajyaSabha: 7,
    legislativeCouncil: 0,
  },
  rajasthan: {
    name: 'Rajasthan',
    mlas: 200,
    mpsLokSabha: 25,
    ulbs: 230,
    rajyaSabha: 10,
    legislativeCouncil: 0,
  },
  sikkim: {
    name: 'Sikkim',
    mlas: 32,
    mpsLokSabha: 1,
    ulbs: 7,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  tamilnadu: {
    name: 'Tamil Nadu',
    mlas: 234,
    mpsLokSabha: 39,
    ulbs: 661,
    rajyaSabha: 18,
    legislativeCouncil: 0,
  },
  telangana: {
    name: 'Telangana',
    mlas: 119,
    mpsLokSabha: 17,
    ulbs: 143,
    rajyaSabha: 7,
    legislativeCouncil: 40,
  },
  tripura: {
    name: 'Tripura',
    mlas: 60,
    mpsLokSabha: 2,
    ulbs: 20,
    rajyaSabha: 1,
    legislativeCouncil: 0,
  },
  uttarpradesh: {
    name: 'Uttar Pradesh',
    mlas: 403,
    mpsLokSabha: 80,
    ulbs: 763,
    rajyaSabha: 31,
    legislativeCouncil: 100,
  },
  uttarakhand: {
    name: 'Uttarakhand',
    mlas: 70,
    mpsLokSabha: 5,
    ulbs: 112,
    rajyaSabha: 3,
    legislativeCouncil: 0,
  },
  westbengal: {
    name: 'West Bengal',
    mlas: 294,
    mpsLokSabha: 42,
    ulbs: 130,
    rajyaSabha: 16,
    legislativeCouncil: 0,
  },
  delhi: {
    name: 'Delhi',
    mlas: 70,
    mpsLokSabha: 7,
    ulbs: 5,
    rajyaSabha: 3,
    legislativeCouncil: 0,
  },
  jammukashmir: {
    name: 'Jammu & Kashmir',
    mlas: 90,
    mpsLokSabha: 5,
    ulbs: 0,
    rajyaSabha: 0,
    legislativeCouncil: 0,
  },
};

export const partyColorMapping: Record<string, { bg: string; fg: string }> = {
  BJP: { bg: '#FF9933', fg: '#FFFFFF' },
  INC: { bg: '#0066FF', fg: '#FFFFFF' },
  Congress: { bg: '#0066FF', fg: '#FFFFFF' },
  AAP: { bg: '#00AEEF', fg: '#FFFFFF' },
  TMC: { bg: '#FF69B4', fg: '#FFFFFF' },
  SP: { bg: '#FF0000', fg: '#FFFFFF' },
  BSP: { bg: '#800080', fg: '#FFFFFF' },
  YSRCP: { bg: '#FFFF00', fg: '#000000' },
  TDP: { bg: '#008000', fg: '#FFFFFF' },
  DMK: { bg: '#FF0000', fg: '#FFFFFF' },
  AIADMK: { bg: '#0000FF', fg: '#FFFFFF' },
  JDU: { bg: '#008080', fg: '#FFFFFF' },
  'LJP(RV)': { bg: '#FFA500', fg: '#FFFFFF' },
  RJD: { bg: '#3FADCC', fg: '#FFFFFF' },
  RLM: { bg: '#A52A2A', fg: '#FFFFFF' },
  HAMS: { bg: '#00FF00', fg: '#000000' },
  'CPI(M)': { bg: '#FF0000', fg: '#FFFFFF' },
  CPI: { bg: '#FF0000', fg: '#FFFFFF' },
  'CPI(ML)': { bg: '#FF0000', fg: '#FFFFFF' },
  AIMIM: { bg: '#32683B', fg: '#FFFFFF' },
  Others: { bg: '#CCCCCC', fg: '#000000' },
};
